#!/usr/bin/env bash

emacs --daemon &
swww-daemon &
waybar &
dunst &
nm-applet --indicator &
udiskie -A -t &
blueman-applet &
lxsession &
foot --server &
ags run &
wl-clip-persist -c both

# ibus-daemon -rxRd
