#!/usr/bin/env bash

emacs --daemon &
swww init
waybar &
dunst &
nm-applet --indicator &
udiskie -A -t &
blueman-applet &
lxsession &
swww img ~/.config/current-wallpaper.*
foot --server &
ags run &

# ibus-daemon -rxRd
