;; -*- lexical-binding: nil; -*-
;; Store autogenerated settings separately
(setq custom-file "~/.config/emacs/custom.el")

(load custom-file t)

;; Load tangled config
(org-babel-load-file
 (expand-file-name "config.org"
                   user-emacs-directory))
(put 'dired-find-alternate-file 'disabled nil)
