;; Load other config files
(load-file "~/.config/emacs/package.el")
(load-file "~/.config/emacs/config.el")
(load-file "~/.config/emacs/keybinding.el")
(load-file "~/.config/emacs/ui.el")
(load-file "~/.config/emacs/editor.el")

;; Store autogenerated settings separately
(setq custom-file "~/.config/emacs/custom.el")

(load custom-file 'noerror)
