require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.icons")
require("user.cmp")
require("user.nvim-tree")
require("user.treesitter")
require("user.autopair")
require("user.comment")
require("user.bufferline")
require("user.lsp")
require("user.lualine")
require("user.telescope")
require("user.rainbow")
require("user.toggleterm")
require("user.gitsigns")
require("user.indentline")
require("user.transparent")
require("user.undotree")
--[[ require("user.noice") ]]
require("user.alpha")
--[[ require("user.debugging") ]]
--[[ require("user.notify") ]]
require("user.colorizer")
